# 新澳燃气 Token 抓取规则
# 使用方法：打开新澳燃气微信小程序，自动抓取 Token 并保存
# 存储 key: xinao_gas.token

[rewrite_local]
^https:\/\/wechatapp\.ecej\.com\/businesshall\/wechatapp\/user\/code2Session url script-response-body https://raw.githubusercontent.com/Nanako718/Scripting/main/Quantumult%20X/js/xinao_gas_token.js

[MITM]
hostname = %APPEND% wechatapp.ecej.com
